STORE_ITEMS = [
    {
        "id": "laptop",
        "name": "Laptop",
        "category": "Matériel",
        "price": 1400,
        "description": "Ordinateur portable standard utilisé pour les hacks sur le terrain.",
        "details": "Suffisant pour les connexions distantes, l'analyse réseau et l'exécution d'exploits de base.",
    },
    {
        "id": "laptop_pro",
        "name": "Laptop Pro",
        "category": "Matériel",
        "price": 2500,
        "description": "Ordinateur portable haut de gamme dédié aux incursions furtives.",
        "details": "Puissance suffisante pour lancer plusieurs attaques simultanées et analyser des paquets à haute vitesse.",
    },
    {
        "id": "flipper_zero",
        "name": "Flipper Zero",
        "category": "Périphérique",
        "price": 950,
        "description": "Multi-outil radio et hacking pour RFID, NFC, IR et Sub-GHz.",
        "details": "Permet d’extraire, cloner et rejouer des signaux électriques et radio pour des attaques physiques ou proches.",
    },
    {
        "id": "rfid_cloner",
        "name": "RFID Cloner",
        "category": "Périphérique",
        "price": 1150,
        "description": "Clone les badges et cartes d'accès magnétiques/RFID.",
        "details": "Très utile pour les accès physiques et le contournement des systèmes de contrôle d'accès.",
    },
    {
        "id": "atm_skimmer",
        "name": "ATM Skimmer",
        "category": "Périphérique",
        "price": 900,
        "description": "Dispositif pour lire et enregistrer les données des cartes bancaires.",
        "details": "Se fixe discrètement sur un terminal bancaire pour capturer les informations de cartes.",
    },
    {
        "id": "card_skimmer",
        "name": "Card Skimmer",
        "category": "Périphérique",
        "price": 750,
        "description": "Version portable de skimmer pour points de vente et bornes NFC.",
        "details": "Conçu pour les petites frappes discrètes sur les lecteurs de cartes de paiement.",
    },
    {
        "id": "drill_kit",
        "name": "Drill Kit",
        "category": "Outils",
        "price": 600,
        "description": "Kit de perçage pour ouvrir les coffrets, boîtiers et caches physiques.",
        "details": "Utile pour les intrusions physiques et l'accès aux points réseau cachés.",
    },
    {
        "id": "ethernet_tap",
        "name": "Ethernet Tap",
        "category": "Réseau",
        "price": 1150,
        "description": "Écoute passive sur un câble réseau physique.",
        "details": "Permet de capturer le trafic sans interrompre la connexion existante.",
    },
    {
        "id": "obd_dongle",
        "name": "OBD Dongle",
        "category": "Véhicule",
        "price": 1100,
        "description": "Accès direct au port OBD-II des véhicules pour lecture et manipulation.",
        "details": "Idéal pour des hacks de véhicules à distance ou pour altérer les systèmes embarqués en toute discrétion.",
    },
    {
        "id": "fiber_tap",
        "name": "Fiber Tap",
        "category": "Réseau",
        "price": 2200,
        "description": "Interception physique d'un câble fibre optique.",
        "details": "Idéal pour des hacks haut débit et des intrusions invisibles sur backbone.",
    },
    {
        "id": "sdr_antenna",
        "name": "SDR Antenna",
        "category": "Radio",
        "price": 1300,
        "description": "Antenne logicielle pour intercepter et analyser des signaux radio.",
        "details": "Utilisée pour écouter, décoder et exploiter des transmissions sécurisées ou propriétaires.",
    },
    {
        "id": "4g_modem",
        "name": "4G Modem",
        "category": "Réseau",
        "price": 850,
        "description": "Connexion mobile anonymisée via carte SIM jetable.",
        "details": "Permet de masquer l'origine d'une attaque lorsque le réseau local n'est pas disponible.",
    },
    {
        "id": "vpn_relay",
        "name": "VPN Relay",
        "category": "Infrastructure",
        "price": 1800,
        "description": "Accès chiffré à un tunnel réseau anonyme.",
        "details": "Masque les origines des attaques et réduit le risque de traçage pendant les hacks longue distance.",
    },
    {
        "id": "serveur_vps",
        "name": "Serveur VPS",
        "category": "Infrastructure",
        "price": 2100,
        "description": "Serveur distant loué pour relayer et anonymiser les attaques.",
        "details": "Relaye les connexions pour contourner les dispositifs de surveillance locaux.",
    },
    {
        "id": "serveur_relay",
        "name": "Serveur Relay",
        "category": "Infrastructure",
        "price": 2300,
        "description": "Infrastructure intermédiaire pour les attaques longue portée.",
        "details": "Facilite le passage à travers plusieurs couches de proxy.",
    },
    {
        "id": "gps_spoofer",
        "name": "GPS Spoofer",
        "category": "Radio",
        "price": 950,
        "description": "Envoie de fausses coordonnées GPS à une cible.",
        "details": "Permet de tromper les systèmes de localisation et d'induire des dispositifs en erreur.",
    },
    {
        "id": "wifi_pineapple",
        "name": "WiFi Pineapple",
        "category": "Réseau",
        "price": 1600,
        "description": "Crée de faux points d'accès WiFi et capture le trafic réseau.",
        "details": "Idéal pour des attaques MiTM et la collecte de données sur les réseaux sans fil.",
    },
    {
        "id": "sdr",
        "name": "SDR",
        "category": "Radio",
        "price": 1250,
        "description": "Radio définie par logiciel pour capturer et analyser des fréquences.",
        "details": "Permet l'écoute et l'analyse de protocoles radio personnalisés.",
    },
    {
        "id": "sdr_radio",
        "name": "SDR Radio",
        "category": "Radio",
        "price": 1450,
        "description": "Récepteur radio spécialisé pour intercepter des transmissions sécurisées.",
        "details": "Utilisé pour écouter et décoder des communications propriétaires ou cryptées.",
    },
    {
        "id": "signal_analyser",
        "name": "Signal Analyser",
        "category": "Radio",
        "price": 1350,
        "description": "Analyse le spectre électromagnétique d'un appareil.",
        "details": "Permet d’identifier les fréquences actives et les signaux ciblés.",
    },
    {
        "id": "signal_jammer",
        "name": "Signal Jammer",
        "category": "Radio",
        "price": 1150,
        "description": "Brouille les fréquences radio dans un rayon défini.",
        "details": "Perturbe les communications ennemies ou empêche les alarmes de recevoir un signal.",
    },
    {
        "id": "rf_jammer",
        "name": "RF Jammer",
        "category": "Radio",
        "price": 1200,
        "description": "Brouille les transmissions sans fil sur plusieurs bandes.",
        "details": "Utile pour des attaques où la cible dépend de communications radio.",
    },
    {
        "id": "spoofing_device",
        "name": "Spoofing Device",
        "category": "Radio",
        "price": 980,
        "description": "Envoie des signaux falsifiés pour tromper des systèmes de détection.",
        "details": "Permet d'usurper l'identité de signaux légitimes.",
    },
    {
        "id": "directional_antenna",
        "name": "Directional Antenna",
        "category": "Radio",
        "price": 1100,
        "description": "Antenne Yagi directionnelle pour étendre la portée des signaux.",
        "details": "Améliore la portée et la précision des transmissions ciblées.",
    },
    {
        "id": "decoder",
        "name": "Decoder",
        "category": "Radio",
        "price": 1250,
        "description": "Déchiffre des protocoles radio propriétaires.",
        "details": "Permet de convertir un signal capturé en données lisibles.",
    },
    {
        "id": "thermal_camera",
        "name": "Thermal Camera",
        "category": "Outils",
        "price": 1150,
        "description": "Caméra thermique détectant les touches récemment pressées.",
        "details": "Idéal pour localiser les pistes de chaleur et les vulnérabilités physiques.",
    },
    {
        "id": "stethoscope_elec",
        "name": "Stethoscope Elec",
        "category": "Outils",
        "price": 900,
        "description": "Capteur pour écouter les composants électroniques protégés.",
        "details": "Permet de surveiller les circuits et d'identifier des états logiques.",
    },
    {
        "id": "bypass_kit",
        "name": "Bypass Kit",
        "category": "Outils",
        "price": 1300,
        "description": "Ensemble d'outils pour court-circuiter les serrures électroniques.",
        "details": "Permet de contourner les dispositifs de verrouillage sans endommager l'équipement.",
    },
    {
        "id": "scada_kit",
        "name": "SCADA Kit",
        "category": "Industrial",
        "price": 1900,
        "description": "Outils d'exploitation des systèmes industriels.",
        "details": "Conçu pour attaquer les systèmes de contrôle et surveillance industriels.",
    },
    {
        "id": "botnet",
        "name": "Botnet",
        "category": "Exploit",
        "price": 2800,
        "description": "Réseau de machines compromises pour amplifier l'attaque.",
        "details": "Augmente la force de l'attaque sur des cibles hautement protégées.",
    },
    {
        "id": "insider",
        "name": "Insider",
        "category": "RP",
        "price": 2200,
        "description": "Complice interne ayant un accès légitime.",
        "details": "Permet d'accéder plus facilement aux zones protégées et aux systèmes internes.",
    },
    {
        "id": "0-day_kit",
        "name": "0-Day Kit",
        "category": "Exploit",
        "price": 3200,
        "description": "Collection d’exploits de failles inconnues pour casser des défenses avancées.",
        "details": "Augmente fortement le potentiel de réussite sur des cibles très protégées, au prix d’un risque élevé.",
    },
]
