TARGETS = [
    {
        "id": "badge_reader_clone",
        "name": "Lecteur de badge / carte RFID",
        "distance_label": "Proximité (≤ 2m)",
        "distance_level": 1,
        "rp_description": "Dupliquer les droits d'accès en reproduisant les données du badge.",
        "tools": ["RFID Cloner", "Flipper Zero"],
        "risk": 1,
        "duration": 5,
    },
    {
        "id": "electronic_lock",
        "name": "Serrure électronique de porte",
        "distance_label": "Proximité (≤ 2m)",
        "distance_level": 1,
        "rp_description": "Trouver le bon code via un bypass kit et accéder à l'intérieur.",
        "tools": ["Laptop", "Bypass Kit"],
        "risk": 2,
        "duration": 25,
    },
    {
        "id": "electronic_safe",
        "name": "Coffre-fort électronique (entrée)",
        "distance_label": "Proximité (≤ 2m)",
        "distance_level": 1,
        "rp_description": "Écouter la serrure et reproduire le rythme des impulsions.",
        "tools": ["Stethoscope Elec", "Laptop"],
        "risk": 4,
        "duration": 150,
    },
    {
        "id": "high_security_safe",
        "name": "Coffre-fort haute sécurité",
        "distance_label": "Proximité (≤ 2m)",
        "distance_level": 1,
        "rp_description": "Combiner forage, analyse de signal et contournement complexe.",
        "tools": ["Drill Kit", "Signal Analyser"],
        "risk": 5,
        "duration": 250,
    },
    {
        "id": "keypad_override",
        "name": "Digicode / pavé numérique",
        "distance_label": "Proximité (≤ 2m)",
        "distance_level": 1,
        "rp_description": "Décoder les entrées récentes avec une caméra thermique pour trouver le code.",
        "tools": ["Thermal Camera", "Laptop"],
        "risk": 2,
        "duration": 19,
    },
    {
        "id": "intercom_spoof",
        "name": "Interphone / contrôle d'accès",
        "distance_label": "Courte portée (≤ 15m)",
        "distance_level": 2,
        "rp_description": "Usurper un signal d'accès pour faire croire à une entrée autorisée.",
        "tools": ["Spoofing Device", "Laptop"],
        "risk": 4,
        "duration": 35,
    },
    {
        "id": "badge_reader_clone",
        "name": "Lecteur de badge / carte RFID",
        "distance_label": "Proximité (≤ 2m)",
        "distance_level": 1,
        "rp_description": "Dupliquer les droits d'accès en reproduisant les données du badge.",
        "tools": ["RFID Cloner", "Flipper Zero"],
        "risk": 1,
        "duration": 5,
    },
    {
        "id": "electronic_lock",
        "name": "Serrure électronique de porte",
        "distance_label": "Proximité (≤ 2m)",
        "distance_level": 1,
        "rp_description": "Trouver le bon code via un bypass kit et accéder à l'intérieur.",
        "tools": ["Laptop", "Bypass Kit"],
        "risk": 2,
        "duration": 25,
    },
    {
        "id": "electronic_safe",
        "name": "Coffre-fort électronique (entrée)",
        "distance_label": "Proximité (≤ 2m)",
        "distance_level": 1,
        "rp_description": "Écouter la serrure et reproduire le rythme des impulsions.",
        "tools": ["Stethoscope Elec", "Laptop"],
        "risk": 4,
        "duration": 150,
    },
    {
        "id": "high_security_safe",
        "name": "Coffre-fort haute sécurité",
        "distance_label": "Proximité (≤ 2m)",
        "distance_level": 1,
        "rp_description": "Combiner forage, analyse de signal et contournement complexe.",
        "tools": ["Drill Kit", "Signal Analyser"],
        "risk": 5,
        "duration": 250,
    },
    {
        "id": "keypad_override",
        "name": "Digicode / pavé numérique",
        "distance_label": "Proximité (≤ 2m)",
        "distance_level": 1,
        "rp_description": "Décoder les entrées récentes avec une caméra thermique pour trouver le code.",
        "tools": ["Thermal Camera", "Laptop"],
        "risk": 2,
        "duration": 19,
    },
    {
        "id": "intercom_spoof",
        "name": "Interphone / contrôle d'accès",
        "distance_label": "Courte portée (≤ 15m)",
        "distance_level": 2,
        "rp_description": "Usurper un signal d'accès pour faire croire à une entrée autorisée.",
        "tools": ["Spoofing Device", "Laptop"],
        "risk": 4,
        "duration": 35,
    },
    {
        "id": "hvac_control_bypass",
        "name": "Système de ventilation (HVAC)",
        "distance_label": "Proximité (≤ 2m)",
        "distance_level": 1,
        "rp_description": "Infiltrer le panneau technique pour couper la ventilation d'une zone ou forcer l'extraction.",
        "tools": ["Laptop", "Bypass Kit"],
        "risk": 1,
        "duration": 45,
    },
    {
        "id": "security_shutter_hack",
        "name": "Rideau métallique de sécurité",
        "distance_label": "Proximité (≤ 2m)",
        "distance_level": 1,
        "rp_description": "Intercepter et rejouer la fréquence radio de la télécommande pour ouvrir le rideau de fer.",
        "tools": ["Flipper Zero", "Signal Analyser"],
        "risk": 2,
        "duration": 40,
    },
    {
        "id": "building_blackout",
        "name": "Contrôleur d'éclairage de zone",
        "distance_label": "Courte portée (≤ 15m)",
        "distance_level": 2,
        "rp_description": "Envoyer une commande de maintenance malveillante pour éteindre toutes les lumières d'un étage.",
        "tools": ["Laptop", "Bypass Kit", "Signal Jammer"],
        "risk": 3,
        "duration": 85,
    },
    {
        "id": "elevator_override",
        "name": "Contrôle d'ascenseur (Service)",
        "distance_label": "Proximité (≤ 2m)",
        "distance_level": 1,
        "rp_description": "Se brancher sur le panneau de la cabine pour forcer l'ascenseur ou bloquer les portes.",
        "tools": ["Laptop", "Bypass Kit"],
        "risk": 2,
        "duration": 65,
    },
]