TARGETS = [
    {
        "id": "badge_reader_clone",
        "name": "Lecteur de badge / carte RFID",
        "distance_label": "Proximité (≤ 2m)",
        "distance_level": 1,
        "rp_description": "Dupliquer les droits d'accès en reproduisant les données du badge.",
        "tools": ["RFID Cloner", "Flipper Zero"],
        "interaction": "sequence",
        "minigame_title": "Reproduction badge RFID",
        "minigame_instruction": "Suivez la séquence d'activation du lecteur pour cloner le badge.",
        "minigame_interaction_hint": "Appuyez sur chaque commande dans l'ordre exact du signal.",
        "risk": 3,
        "duration": 95,
        "hint": "Suivre la bonne séquence pour cloner le badge avant expiration.",
    },
    {
        "id": "electronic_lock",
        "name": "Serrure électronique de porte",
        "distance_label": "Proximité (≤ 2m)",
        "distance_level": 1,
        "rp_description": "Trouver le bon code via un bypass kit et accéder à l'intérieur.",
        "tools": ["Laptop", "Bypass Kit"],
        "interaction": "keypad",
        "minigame_title": "Bypass du clavier électronique",
        "minigame_instruction": "Entrez le code numérique du clavier pour déverrouiller la porte.",
        "minigame_interaction_hint": "Saisissez le bon code sur le pavé numérique et validez.",
        "risk": 4,
        "duration": 130,
        "hint": "Changer les paramètres du contrôleur de porte pour le déverrouiller.",
    },
    {
        "id": "electronic_safe",
        "name": "Coffre-fort électronique (entrée)",
        "distance_label": "Proximité (≤ 2m)",
        "distance_level": 1,
        "rp_description": "Écouter la serrure et reproduire le rythme des impulsions.",
        "tools": ["Stethoscope Elec", "Laptop"],
        "interaction": "thermal",
        "minigame_title": "Analyse thermique serrure",
        "minigame_instruction": "Cliquez sur les touches les plus chaudes dans l'ordre décroissant.",
        "minigame_interaction_hint": "Repérez les températures les plus élevées et sélectionnez-les successivement.",
        "risk": 3,
        "duration": 120,
        "hint": "Cliquer sur les zones les plus chaudes pour deviner la combinaison.",
    },
    {
        "id": "high_security_safe",
        "name": "Coffre-fort haute sécurité",
        "distance_label": "Proximité (≤ 2m)",
        "distance_level": 1,
        "rp_description": "Combiner forage, analyse de signal et contournement complexe.",
        "tools": ["Drill Kit", "Signal Analyser"],
        "interaction": "firewall",
        "minigame_title": "Contournement de sécurité de coffre-fort",
        "minigame_instruction": "Ajustez les commutateurs pour ouvrir un chemin à travers le pare-feu de sécurité.",
        "minigame_interaction_hint": "Activez les bons commutateurs pour débloquer l'accès.",
        "risk": 5,
        "duration": 190,
        "hint": "Compléter plusieurs étapes en chaîne pour pénétrer la sécurité.",
    },
    {
        "id": "keypad_override",
        "name": "Digicode / pavé numérique",
        "distance_label": "Proximité (≤ 2m)",
        "distance_level": 1,
        "rp_description": "Décoder les entrées récentes avec une caméra thermique pour trouver le code.",
        "tools": ["Thermal Camera", "Laptop"],
        "interaction": "puzzle",
        "minigame_title": "Décodage digicode thermique",
        "minigame_instruction": "Reconstituez la séquence de touches chaude pour deviner le code.",
        "minigame_interaction_hint": "Utilisez les indices thermiques pour recomposer la bonne suite.",
        "risk": 3,
        "duration": 105,
        "hint": "Analyser les touches chaudes et reconstituer la séquence correcte.",
    },
    {
        "id": "intercom_spoof",
        "name": "Interphone / contrôle d'accès",
        "distance_label": "Courte portée (≤ 15m)",
        "distance_level": 2,
        "rp_description": "Usurper un signal d'accès pour faire croire à une entrée autorisée.",
        "tools": ["Spoofing Device", "Laptop"],
        "interaction": "bruteforce",
        "minigame_title": "Usurpation interphone",
        "minigame_instruction": "Démarrez le processus de force brute sur l'accès audio et attendez le succès.",
        "minigame_interaction_hint": "Lancez l'attaque et surveillez la progression jusqu'à l'autorisation.",
        "risk": 4,
        "duration": 140,
        "hint": "Forcer les commandes du contrôleur lorsque le signal est instable.",
    },
]
