TARGETS = [
    {
        "id": "badge_reader_clone",
        "name": "Lecteur de badge / carte RFID",
        "distance_label": "Proximité (≤ 2m)",
        "distance_level": 1,
        "rp_description": "Dupliquer les droits d'accès en reproduisant les données du badge.",
        "tools": ["RFID Cloner", "Flipper Zero"],
        "interaction": "sequence",
        "risk": 3,
        "duration": 95,
        "hint": "Suivre la bonne séquence pour cloner le badge avant expiration.",
    },
    {
        "id": "electronic_lock",
        "name": "Serrure électronique de porte",
        "distance_label": "Proximité (≤ 2m)",
        "distance_level": 1,
        "rp_description": "Trouver le bon code via un bypass kit et accéder à l'intérieur.",
        "tools": ["Laptop", "Bypass Kit"],
        "interaction": "terminal",
        "risk": 4,
        "duration": 130,
        "hint": "Changer les paramètres du contrôleur de porte pour le déverrouiller.",
    },
    {
        "id": "electronic_safe",
        "name": "Coffre-fort électronique (entrée)",
        "distance_label": "Proximité (≤ 2m)",
        "distance_level": 1,
        "rp_description": "Écouter la serrure et reproduire le rythme des impulsions.",
        "tools": ["Stethoscope Elec", "Laptop"],
        "interaction": "thermal",
        "risk": 3,
        "duration": 120,
        "hint": "Cliquer sur les zones les plus chaudes pour deviner la combinaison.",
    },
    {
        "id": "high_security_safe",
        "name": "Coffre-fort haute sécurité",
        "distance_label": "Proximité (≤ 2m)",
        "distance_level": 1,
        "rp_description": "Combiner forage, analyse de signal et contournement complexe.",
        "tools": ["Drill Kit", "Signal Analyser"],
        "interaction": "chain",
        "risk": 5,
        "duration": 190,
        "hint": "Compléter plusieurs étapes en chaîne pour pénétrer la sécurité.",
    },
    {
        "id": "keypad_override",
        "name": "Digicode / pavé numérique",
        "distance_label": "Proximité (≤ 2m)",
        "distance_level": 1,
        "rp_description": "Décoder les entrées récentes avec une caméra thermique pour trouver le code.",
        "tools": ["Thermal Camera", "Laptop"],
        "interaction": "puzzle",
        "risk": 3,
        "duration": 105,
        "hint": "Analyser les touches chaudes et reconstituer la séquence correcte.",
    },
    {
        "id": "intercom_spoof",
        "name": "Interphone / contrôle d'accès",
        "distance_label": "Courte portée (≤ 15m)",
        "distance_level": 2,
        "rp_description": "Usurper un signal d'accès pour faire croire à une entrée autorisée.",
        "tools": ["Spoofing Device", "Laptop"],
        "interaction": "bruteforce",
        "risk": 4,
        "duration": 140,
        "hint": "Forcer les commandes du contrôleur lorsque le signal est instable.",
    },
]
