TARGETS = [
    {
        "id": "local_ip_camera",
        "name": "Caméra IP locale",
        "distance_label": "Courte portée (≤ 15m)",
        "distance_level": 2,
        "rp_description": "Scanner le réseau local puis casser le mot de passe de la caméra.",
        "tools": ["Laptop", "WiFi Pineapple"],
        "interaction": "bruteforce",
        "risk": 3,
        "duration": 110,
        "hint": "Surveiller le trafic WiFi et déclencher l'attaque de force brute au bon moment.",
    },
    {
        "id": "local_alarm",
        "name": "Système d'alarme local",
        "distance_label": "Proximité (≤ 2m)",
        "distance_level": 1,
        "rp_description": "Décoder la fréquence du panneau d'alarme pour le neutraliser silencieusement.",
        "tools": ["Signal Jammer", "Laptop"],
        "interaction": "frequency",
        "risk": 3,
        "duration": 100,
        "hint": "Trouver le signal porteur qui active l'alarme et l'interrompre.",
    },
    {
        "id": "nvr_dvr",
        "name": "NVR / DVR local",
        "distance_label": "Courte portée (≤ 15m)",
        "distance_level": 2,
        "rp_description": "Exploiter un port ouvert pour prendre le contrôle de l'enregistreur.",
        "tools": ["Laptop", "Ethernet Tap"],
        "interaction": "terminal",
        "risk": 4,
        "duration": 120,
        "hint": "Envoyer la commande d'exploitation via le port découverte.",
    },
    {
        "id": "network_alarm",
        "name": "Système d'alarme réseau",
        "distance_label": "Portée moyenne (≤ 50m)",
        "distance_level": 3,
        "rp_description": "Injecter des paquets corrompus dans le bus de signalisation réseau.",
        "tools": ["Laptop", "Directional Antenna"],
        "interaction": "radio",
        "risk": 4,
        "duration": 130,
        "hint": "Assembler les bons fragments de paquets pour prendre le contrôle.",
    },
    {
        "id": "centralized_cameras",
        "name": "Caméras réseau centralisées",
        "distance_label": "Portée étendue (≤ 2km)",
        "distance_level": 5,
        "rp_description": "Pivotner depuis un relais VPN pour atteindre un système centralisé.",
        "tools": ["Laptop", "VPN Relay", "4G Modem"],
        "interaction": "chain",
        "risk": 5,
        "duration": 160,
        "hint": "Combiner plusieurs étapes pour pénétrer la surveillance centralisée.",
    },
    {
        "id": "urban_surveillance",
        "name": "Système de surveillance urbain",
        "distance_label": "San Andreas complet",
        "distance_level": 6,
        "rp_description": "Créer une chaîne d'exploits complète pour atteindre l'infrastructure.",
        "tools": ["Laptop", "Serveur Relay"],
        "interaction": "stages",
        "risk": 5,
        "duration": 180,
        "hint": "Maîtriser plusieurs phases pour désactiver la surveillance urbaine.",
    },
]
