TARGETS = [
    {
        "id": "local_ip_camera",
        "name": "Caméra IP locale",
        "distance_label": "Courte portée (≤ 15m)",
        "distance_level": 2,
        "rp_description": "Scanner le réseau local puis casser le mot de passe de la caméra.",
        "tools": ["Laptop", "WiFi Pineapple"],
        "risk": 3,
        "duration": 110,
    },
    {
        "id": "scan_copy_phone",
        "name": "Scan & Copy Data Phone",
        "distance_label": "Courte portée (≤ 5m)",
        "distance_level": 2,
        "rp_description": "Scan le téléphone de la personne visé et copie ses données personnelles (photo, sms, localisations, etc) ou pirate ses comptes (facebook, instagram, snapchat, etc).",
        "tools": ["Laptop", "WiFi Pineapple"],
        "risk": 3,
        "duration": 15,
    },
    {
        "id": "bulle_cctv",
        "name": "CCTV Break Down",
        "distance_label": "Portée moyenne (≤ 50m)",
        "distance_level": 3,
        "rp_description": "Scanne l'entierté du reseau communication interne de caméras CCTV d'un site et exploite une vulnérabilité Zero Day pour les faire planter dans un rayon de 50M autour du brouilleur.",
        "tools": ["Laptop", "CCTV Exploit Kit", "Signal Jammer", "Directional Antenna + Amplifier arduino kit"],
        "risk": 4,
        "duration": 350,
    },
    {
        "id": "local_alarm",
        "name": "Système d'alarme local",
        "distance_label": "Proximité (≤ 2m)",
        "distance_level": 1,
        "rp_description": "Décoder la fréquence du panneau d'alarme pour le neutraliser silencieusement.",
        "tools": ["Signal Jammer", "Laptop"],
        "risk": 3,
        "duration": 110,
    },
    {
        "id": "nvr_dvr",
        "name": "NVR / DVR local | Stop CCTV recording",
        "distance_label": "Proximité (≤ 2m)",
        "distance_level": 1,
        "rp_description": "Exploiter un port ouvert pour prendre le contrôle de l'enregistreur CCTV pour le stoper net.",
        "tools": ["Laptop", "Ethernet Tap", "Bypass Kit", "internet access with infected USB driver internet port"],
        "risk": 4,
        "duration": 135,
    },
    {
        "id": "network_alarm",
        "name": "Système d'alarme réseau",
        "distance_label": "Portée moyenne (≤ 50m)",
        "distance_level": 3,
        "rp_description": "Injecter des paquets corrompus dans le bus de signalisation réseau.",
        "tools": ["Laptop", "Directional Antenna"],
        "risk": 4,
        "duration": 148,
    },
    {
        "id": "urban_surveillance",
        "name": "Système de surveillance urbain",
        "distance_label": "San Andreas complet",
        "distance_level": 6,
        "rp_description": "Créer une chaîne d'exploitation complète pour atteindre l'infrastructure CCTV municipale et pouvoir alterner les vision et stoper le direct des caméras de la ville.",
        "tools": ["Laptop", "Serveur Relay", "0-Day Kit", "Botnet", "Insider", "Signal Jammer", "Directional Antenna + Amplifier arduino kit"],
        "risk": 5,
        "duration": 325,
    },
    {
        "id": "intercom_megaphone",
        "name": "Intercoms / Mégaphones",
        "distance_label": "Portée moyenne (≤ 50m)",
        "distance_level": 3,
        "rp_description": "Scanner l'entierté du reseau communication interne de intercoms et mégaphones d'un site et exploite une vulnérabilité Zero Day pour les faire planter dans un rayon de 50M autour du brouilleur.",
        "tools": ["Laptop", "Signal Jammer", "Directional Antenna"],
        "risk": 3,
        "duration": 35,
    },
    {
        "id": "radar_detection_systems",
        "name": "Systèmes de détection radar",
        "distance_label": "Portée longue (≤ 1km)",
        "distance_level": 5,
        "rp_description": "Neutralisation des systèmes de détection radar par brouillage à large bande ou émission de leurres électroniques.",
        "tools": ["Laptop", "Radar Jammer (High Power)", "Signal Generator", "Directional Antenna (Wide Beam)", "Spectrum Analyzer"],
        "risk": 5,
        "duration": 45,
    },
    {
        "id": "drone_control_systems",
        "name": "Systèmes de contrôle de drones",
        "distance_label": "Portée longue (≤ 500m)",
        "distance_level": 4,
        "rp_description": "Interférence avec les fréquences de contrôle (2.4GHz / 5.8GHz) pour forcer l'atterrissage d'urgence ou la perte de contrôle.",
        "tools": ["Laptop", "Drone Jammer", "Directional Antenna", "Spectrum Analyzer"],
        "risk": 5,
        "duration": 60,
    },
    {
        "id": "asset_tracking_systems",
        "name": "Systèmes de suivi GPS / RFID",
        "distance_label": "Portée moyenne (≤ 100m)",
        "distance_level": 3,
        "rp_description": "Brouillage des signaux GPS et RFID pour masquer la localisation des véhicules ou du personnel.",
        "tools": ["Laptop", "GPS Jammer", "RFID Jammer", "Portable Power Bank"],
        "risk": 4,
        "duration": 90,
    },
    {
    "id": "rfid_data_theft",
    "name": "Vol de données RFID",
    "distance_label": "Proximité (≤ 1m)",
    "distance_level": 1,
    "rp_description": "Lecture et clonage de cartes RFID/NFC à courte portée pour contourner les contrôles d'accès.",
    "tools": ["Laptop", "NFC/RFID Reader Writer", "Proxmark3"],
    "risk": 4,
    "duration": 15,
},
{
    "id": "payment_terminal_attack",
    "name": "Attaque de terminaux de paiement",
    "distance_label": "Proximité (≤ 1m)",
    "distance_level": 1,
    "rp_description": "Injection de commandes dans les terminaux de paiement sans contact pour voler les données de transaction.",
    "tools": ["Laptop", "EMV Card Reader", "Script injecteur"],
    "risk": 5,
    "duration": 45,
},
{
    "id": "industrial_control_system",
    "name": "Système de contrôle industriel (SCADA)",
    "distance_label": "Portée longue (≤ 1km)",
    "distance_level": 5,
    "rp_description": "Infiltration du réseau SCADA pour manipuler les processus industriels (arrêt, surcharge, etc.).",
    "tools": ["Laptop", "Industrial Exploit Framework", "Radio Hacking Suite", "Modbus Scanner"],
    "risk": 5,
    "duration": 480,
},
{
    "id": "automatic_gates_barrier",
    "name": "Portails et barrières automatiques",
    "distance_label": "Portée moyenne (≤ 50m)",
    "distance_level": 3,
    "rp_description": "Capture et rejeu des signaux des télécommandes pour ouvrir les barrières d'accès.",
    "tools": ["Laptop", "SDR (Software Defined Radio)", "RF Recorder"],
    "risk": 4,
    "duration": 35,
},
{
    "id": "automatic_doors_sensors",
    "name": "Capteurs de portes automatiques",
    "distance_label": "Proximité (≤ 10m)",
    "distance_level": 2,
    "rp_description": "Brouillage ou simulation de présence pour ouvrir les portes automatiques sans autorisation.",
    "tools": ["Laptop", "RF Emitter", "Signal Detector"],
    "risk": 3,
    "duration": 45,
},
{
    "id": "medical_devices",
    "name": "Dispositifs médicaux connectés",
    "distance_label": "Portée moyenne (≤ 50m)",
    "distance_level": 3,
    "rp_description": "Interférence ou piratage des dispositifs médicaux sans fil (pompes à insuline, pacemakers, etc.).",
    "tools": ["Laptop", "Medical Device Scanner", "Radio Hacking Suite"],
    "risk": 5,
    "duration": 350,
},
{
    "id": "smart_locks_system",
    "name": "Système de serrures intelligentes",
    "distance_label": "Proximité (≤ 10m)",
    "distance_level": 2,
    "rp_description": "Contournement des serrures connectées via Bluetooth, Zigbee ou Wi-Fi.",
    "tools": ["Laptop", "Bluetooth Scanner", "Zigbee Sniffer", "Smart Lock Exploit Kit"],
    "risk": 4,
    "duration": 10,
},
{
    "id": "garage_door_openers",
    "name": "Ouvre-portes de garage",
    "distance_label": "Proximité (≤ 50m)",
    "distance_level": 3,
    "rp_description": "Capture des fréquences radio des télécommandes pour ouvrir les garages.",
    "tools": ["Laptop", "RF Recorder", "Signal Generator"],
    "risk": 3,
    "duration": 10,
},
{
    "id": "smart_meter_hack",
    "name": "Compteurs intelligents (Smart Meters)",
    "distance_label": "Portée moyenne (≤ 100m)",
    "distance_level": 3,
    "rp_description": "Manipulation des compteurs électriques intelligents pour fausser la consommation d'énergie.",
    "tools": ["Laptop", "Smart Meter Reader", "RF Antenna"],
    "risk": 4,
    "duration": 60,
},
{
    "id": "parking_systems",
    "name": "Systèmes de paiement de parking",
    "distance_label": "Portée moyenne (≤ 50m)",
    "distance_level": 3,
    "rp_description": "Contournement des barrières de parking et des systèmes de paiement.",
    "tools": ["Laptop", "RF Recorder", "Card Emulator"],
    "risk": 4,
    "duration": 15,
},
{
    "id": "heating_cooling_systems",
    "name": "Systèmes de chauffage et climatisation (HVAC)",
    "distance_label": "Portée moyenne (≤ 100m)",
    "distance_level": 3,
    "rp_description": "Prise de contrôle des systèmes CVC pour créer des conditions extrêmes.",
    "tools": ["Laptop", "HVAC Hacking Tool", "Network Scanner"],
    "risk": 3,
    "duration": 150,
},
{
    "id": "elevator_controls",
    "name": "Contrôles d'ascenseurs",
    "distance_label": "Proximité (≤ 10m)",
    "distance_level": 2,
    "rp_description": "Accès non autorisé aux systèmes de contrôle des ascenseurs.",
    "tools": ["Laptop", "Elevator Protocol Analyzer", "Maintenance Key"],
    "risk": 4,
    "duration": 25,
},
{
    "id": "speaker_system_override",
    "name": "Prise de contrôle de systèmes de haut-parleurs",
    "distance_label": "Portée moyenne (≤ 100m)",
    "distance_level": 3,
    "rp_description": "Hijacking des systèmes de sonorisation pour diffuser des messages ou des bruits.",
    "tools": ["Laptop", "Audio Amplifier", "Wireless Transmitter"],
    "risk": 3,
    "duration": 12,
},
]