TARGETS = [
    {
        "id": "atm_clone",
        "name": "Distributeur automatique (ATM)",
        "distance_label": "Proximité (≤ 2m)",
        "distance_level": 1,
        "rp_description": "Installer un skimmer et extraire les données de la carte discrètement.",
        "tools": ["ATM Skimmer", "Laptop"],
        "risk": 4,
        "duration": 130,
    },
    {
        "id": "atm_open",
        "name": "ATM Cracking - Faux retrait",
        "distance_label": "Proximité (≤ 2m)",
        "distance_level": 1,
        "rp_description": "Installer un skimmer et extraire les données de la carte discrètement.",
        "tools": ["ATM Skimmer", "Laptop", "Card Cloner", "Crack Phone with linked card reader", "USB Crack Credit Card"],
        "risk": 4,
        "duration": 135,
    },
    {
        "id": "tpe_intercept",
        "name": "Borne de paiement (TPE)",
        "distance_label": "Proximité (≤ 2m)",
        "distance_level": 1,
        "rp_description": "Intercepter une transaction NFC et reproduire la page de paiement.",
        "tools": ["Card Skimmer", "Flipper Zero"],
        "risk": 4,
        "duration": 110,
    },
    {
        "id": "tpe_intercept",
        "name": "Fake payment au TPE",
        "distance_label": "Proximité (≤ 2m)",
        "distance_level": 1,
        "rp_description": "Tenter de faire un faux payment a un TPE sans perdre d'argent sur la CB.",
        "tools": ["Card Skimmer", "Flipper Zero"],
        "risk": 2,
        "duration": 5,
    },
    {
        "id": "traffic_lights",
        "name": "Feux de circulation",
        "distance_label": "Courte portée (≤ 15m)",
        "distance_level": 2,
        "rp_description": "Injecter un signal malformé pour prendre le contrôle des feux.",
        "tools": ["SDR", "Laptop", "Signal Jammer", "Traffic controller", "SADOT Traffic Light Maintenance Kit"],
        "risk": 1,
        "duration": 176,
    },
    {
        "id": "automatic_gate",
        "name": "Portails automatiques",
        "distance_label": "Proximité (≤ 2m)",
        "distance_level": 1,
        "rp_description": "Chercher la fréquence d'ouverture et forcer l'ouverture d'un portail ou auter porte automatique.",
        "tools": ["RF Jammer", "Flipper Zero", "Cralwer Signal", "Signal Analyser"],
        "risk": 1,
        "duration": 23,
    },
    {
        "id": "electrical_grid",
        "name": "Infrastructure électrique",
        "distance_label": "Portée moyenne (≤ 50m)",
        "distance_level": 3,
        "rp_description": "Exploiter un SCADA mal configuré pour perturber un poste électrique et couper l'éléctricité.",
        "tools": ["SCADA Kit", "Laptop", "EMC Jammer", "Signal Analyser", "Elec Controler"],
        "risk": 5,
        "duration": 189,
    },
    {
        "id": "fiber_network",
        "name": "Réseau fibre / télécom",
        "distance_label": "Portée étendue (≤ 2km)",
        "distance_level": 5,
        "rp_description": "Intercepter le trafic fibre et analyser les paquets à distance.",
        "tools": ["Fiber Tap", "Laptop"],
        "risk": 5,
        "duration": 180,
    },
    {
        "id": "off_network",
        "name": "Désert réseaux",
        "distance_label": "Portée moyenne (≤ 50m)",
        "distance_level": 5,
        "rp_description": "Crée une bulle debrouillage des onde réseaux mobile (2G/3G/4G/5G).",
        "tools": ["Fiber Tap", "Laptop", "Mobile Jammer", "Signal Analyser"],
        "risk": 1,
        "duration": 10,
    },
]