TARGETS = [
    {
        "id": "atm_clone",
        "name": "Distributeur automatique (ATM)",
        "distance_label": "Proximité (≤ 2m)",
        "distance_level": 1,
        "rp_description": "Installer un skimmer et extraire les données de la carte discrètement.",
        "tools": ["ATM Skimmer", "Laptop"],
        "interaction": "sequence",
        "minigame_title": "Activation skimmer ATM",
        "minigame_instruction": "Reproduisez la séquence de commande du boîtier pour démarrer le skimmer.",
        "minigame_interaction_hint": "Appuyez sur les boutons dans l'ordre exact indiqué par l'interface.",
        "risk": 4,
        "duration": 130,
        "hint": "Suivre la suite de boutons du boîtier pour activer le skimmer.",
    },
    {
        "id": "tpe_intercept",
        "name": "Borne de paiement (TPE)",
        "distance_label": "Proximité (≤ 2m)",
        "distance_level": 1,
        "rp_description": "Intercepter une transaction NFC et reproduire la page de paiement.",
        "tools": ["Card Skimmer", "Flipper Zero"],
        "interaction": "wiring",
        "minigame_title": "Câblage TPE",
        "minigame_instruction": "Reliez les composants NFC dans le bon ordre pour activer la copie.",
        "minigame_interaction_hint": "Sélectionnez d'abord le composant source puis sa destination.",
        "risk": 4,
        "duration": 110,
        "hint": "Relier les composants dans l'ordre pour activer le skimmer mobile.",
    },
    {
        "id": "parking_meter",
        "name": "Horodateur / parking",
        "distance_label": "Proximité (≤ 2m)",
        "distance_level": 1,
        "rp_description": "Rejouer un signal enregistré pour voler le paiement sans attirer l'attention.",
        "tools": ["Flipper Zero", "Laptop"],
        "interaction": "bruteforce",
        "minigame_title": "Rejeu de signal parking",
        "minigame_instruction": "Lancez l'attaque de répétition et laissez le système trouver la bonne clé.",
        "minigame_interaction_hint": "Démarrez le processus puis attendez la fin du bruteforce.",
        "risk": 3,
        "duration": 95,
        "hint": "Lancer l'attaque de replay et surveiller les interruptions du bus.",
    },
    {
        "id": "traffic_lights",
        "name": "Feux de circulation",
        "distance_label": "Courte portée (≤ 15m)",
        "distance_level": 2,
        "rp_description": "Injecter un signal malformé pour prendre le contrôle des feux.",
        "tools": ["SDR", "Laptop"],
        "interaction": "pattern",
        "minigame_title": "Synchronisation par motif",
        "minigame_instruction": "Reproduisez le motif de signal correct pour reprendre le contrôle des feux.",
        "minigame_interaction_hint": "Cliquez sur les chiffres dans le bon ordre pour valider le motif.",
        "risk": 4,
        "duration": 120,
        "hint": "Scanner les fréquences du contrôleur et synchroniser l'injection.",
    },
    {
        "id": "automatic_gate",
        "name": "Portails automatiques",
        "distance_label": "Proximité (≤ 2m)",
        "distance_level": 1,
        "rp_description": "Chercher la fréquence d'ouverture et forcer la serrure électronique.",
        "tools": ["RF Jammer", "Flipper Zero"],
        "interaction": "terminal",
        "minigame_title": "Commande portail automatique",
        "minigame_instruction": "Entrez la commande de déverrouillage du système de portail.",
        "minigame_interaction_hint": "Saisissez la commande correcte et confirmez-la dans le terminal.",
        "risk": 3,
        "duration": 105,
        "hint": "Envoyer les commandes du module et obtenir l'autorisation d'ouverture.",
    },
    {
        "id": "electrical_grid",
        "name": "Infrastructure électrique",
        "distance_label": "Portée moyenne (≤ 50m)",
        "distance_level": 3,
        "rp_description": "Exploiter un SCADA mal configuré pour perturber un poste électrique.",
        "tools": ["SCADA Kit", "Laptop"],
        "interaction": "radio",
        "minigame_title": "Contrôle radio SCADA",
        "minigame_instruction": "Recomposez les fragments radio pour prendre le contrôle du SCADA.",
        "minigame_interaction_hint": "Choisissez les bons fragments dans l'ordre pour décrypter le message.",
        "risk": 5,
        "duration": 170,
        "hint": "Assembler les fragments radio du système industriel pour prendre la main.",
    },
    {
        "id": "fiber_network",
        "name": "Réseau fibre / télécom",
        "distance_label": "Portée étendue (≤ 2km)",
        "distance_level": 5,
        "rp_description": "Intercepter le trafic fibre et analyser les paquets à distance.",
        "tools": ["Fiber Tap", "Laptop"],
        "interaction": "memory",
        "minigame_title": "Récolte de données mémoire",
        "minigame_instruction": "Mémorisez la séquence d'analyse puis reproduisez-la pour capturer le trafic.",
        "minigame_interaction_hint": "Reproduisez la séquence observée pour valider l'interception.",
        "risk": 5,
        "duration": 180,
        "hint": "Maintenir la connexion tout en franchissant plusieurs niveaux de sécurité.",
    },
]
