TARGETS = [
    {
        "id": "atm_clone",
        "name": "Distributeur automatique (ATM)",
        "distance_label": "Proximité (≤ 2m)",
        "distance_level": 1,
        "rp_description": "Installer un skimmer et extraire les données de la carte discrètement.",
        "tools": ["ATM Skimmer", "Laptop"],
        "interaction": "sequence",
        "risk": 4,
        "duration": 130,
        "hint": "Suivre la suite de boutons du boîtier pour activer le skimmer.",
    },
    {
        "id": "tpe_intercept",
        "name": "Borne de paiement (TPE)",
        "distance_label": "Proximité (≤ 2m)",
        "distance_level": 1,
        "rp_description": "Intercepter une transaction NFC et reproduire la page de paiement.",
        "tools": ["Card Skimmer", "Flipper Zero"],
        "interaction": "wiring",
        "risk": 4,
        "duration": 110,
        "hint": "Relier les composants dans l'ordre pour activer le skimmer mobile.",
    },
    {
        "id": "parking_meter",
        "name": "Horodateur / parking",
        "distance_label": "Proximité (≤ 2m)",
        "distance_level": 1,
        "rp_description": "Rejouer un signal enregistré pour voler le paiement sans attirer l'attention.",
        "tools": ["Flipper Zero", "Laptop"],
        "interaction": "bruteforce",
        "risk": 3,
        "duration": 95,
        "hint": "Lancer l'attaque de replay et surveiller les interruptions du bus.",
    },
    {
        "id": "traffic_lights",
        "name": "Feux de circulation",
        "distance_label": "Courte portée (≤ 15m)",
        "distance_level": 2,
        "rp_description": "Injecter un signal malformé pour prendre le contrôle des feux.",
        "tools": ["SDR", "Laptop"],
        "interaction": "frequency",
        "risk": 4,
        "duration": 120,
        "hint": "Scanner les fréquences du contrôleur et synchroniser l'injection.",
    },
    {
        "id": "automatic_gate",
        "name": "Portails automatiques",
        "distance_label": "Proximité (≤ 2m)",
        "distance_level": 1,
        "rp_description": "Chercher la fréquence d'ouverture et forcer la serrure électronique.",
        "tools": ["RF Jammer", "Flipper Zero"],
        "interaction": "terminal",
        "risk": 3,
        "duration": 105,
        "hint": "Envoyer les commandes du module et obtenir l'autorisation d'ouverture.",
    },
    {
        "id": "electrical_grid",
        "name": "Infrastructure électrique",
        "distance_label": "Portée moyenne (≤ 50m)",
        "distance_level": 3,
        "rp_description": "Exploiter un SCADA mal configuré pour perturber un poste électrique.",
        "tools": ["SCADA Kit", "Laptop"],
        "interaction": "radio",
        "risk": 5,
        "duration": 170,
        "hint": "Assembler les fragments radio du système industriel pour prendre la main.",
    },
    {
        "id": "fiber_network",
        "name": "Réseau fibre / télécom",
        "distance_label": "Portée étendue (≤ 2km)",
        "distance_level": 5,
        "rp_description": "Intercepter le trafic fibre et analyser les paquets à distance.",
        "tools": ["Fiber Tap", "Laptop"],
        "interaction": "stages",
        "risk": 5,
        "duration": 180,
        "hint": "Maintenir la connexion tout en franchissant plusieurs niveaux de sécurité.",
    },
]
