TARGETS = [
    {
        "id": "911_hacks",
        "name": "Faux apell au 911",
        "distance_label": "San Andreas + Robada",
        "distance_level": 7,
        "rp_description": "Simuler un appel d'urgence pour détourner les ressources policières ou créer une diversion.",
        "tools": ["911 Spoofer", "Laptop", "Voice Changer", "Fake Caller ID", "UTK Police Scanner"],
        "risk": 3,
        "duration": 150,
    },
    {
        "id": "mdt_hacks",
        "name": "Hacks du MDT (Mobile Data Terminal)",
        "distance_label": "San Andreas + Robada",
        "distance_level": 7,
        "rp_description": "Accéder au MDT pour obtenir des informations sur les unités policières, les appels en cours et les emplacements des patrouilles.",
        "tools": ["MDT Exploit Kit", "Police Laptop", "Signal Jammer", "UTK Police Scanner", "Scanner & Reader Radio Frequencies"],
        "risk": 3,
        "duration": 305,
    },
    {
        "id": "poste_police_hacks",
        "name": "Hacks de postes de police",
        "distance_label": "San Andreas + Robada",
        "distance_level": 7,
        "rp_description": "Accéder aux systèmes des postes de police et commissariats pour obtenir des informations sensibles.",
        "tools": ["MDT Exploit Kit", "Police Laptop", "Signal Jammer", "UTK Police Scanner", "Scanner & Reader Radio Frequencies"],
        "risk": 5,
        "duration": 251,
    },
    {
        "id": "flood_911",
        "name": "Flood 911",
        "distance_label": "San Andreas + Robada",
        "distance_level": 7,
        "rp_description": "Envoyer un grand nombre d'appels fictifs au 911 pour surcharger le système.",
        "tools": ["911 Spoofer", "Laptop", "Voice Changer", "Fake Caller ID"],
        "risk": 5,
        "duration": 25,
    },
    {
        "id": "axon_body_cam_hacks",
        "name": "Hacks des caméras corporelles Axon",
        "distance_label": "Courte portée (≤ 15m)",
        "distance_level": 2,
        "rp_description": "Injecter un signal malformé pour stoper et/ou brouillez les body cams.",
        "tools": ["SDR", "Laptop", "Signal Jammer", "Body Cam Controller", "SADOT Body Cam Maintenance Kit"],
        "risk": 2,
        "duration": 140,
    },
]