TARGETS = [
    {
        "id": "911_hacks",
        "name": "Faux apell au 911",
        "distance_label": "San Andreas + Robada",
        "distance_level": 7,
        "rp_description": "Simuler un appel d'urgence pour détourner les ressources policières ou créer une diversion.",
        "tools": ["911 Spoofer", "Laptop", "Voice Changer", "Fake Caller ID", "UTK Police Scanner"],
        "risk": 3,
        "duration": 150,
    },
    {
        "id": "mdt_hacks",
        "name": "Hacks du MDT (Mobile Data Terminal)",
        "distance_label": "San Andreas + Robada",
        "distance_level": 7,
        "rp_description": "Accéder au MDT pour obtenir des informations sur les unités policières, les appels en cours et les emplacements des patrouilles.",
        "tools": ["MDT Exploit Kit", "Police Laptop", "Signal Jammer", "UTK Police Scanner", "Scanner & Reader Radio Frequencies"],
        "risk": 3,
        "duration": 305,
    },
    {
        "id": "poste_police_hacks",
        "name": "Hacks de postes de police",
        "distance_label": "San Andreas + Robada",
        "distance_level": 7,
        "rp_description": "Accéder aux systèmes des postes de police et commissariats pour obtenir des informations sensibles.",
        "tools": ["MDT Exploit Kit", "Police Laptop", "Signal Jammer", "UTK Police Scanner", "Scanner & Reader Radio Frequencies"],
        "risk": 5,
        "duration": 251,
    },
    {
        "id": "flood_911",
        "name": "Flood 911",
        "distance_label": "San Andreas + Robada",
        "distance_level": 7,
        "rp_description": "Envoyer un grand nombre d'appels fictifs au 911 pour surcharger le système.",
        "tools": ["911 Spoofer", "Laptop", "Voice Changer", "Fake Caller ID"],
        "risk": 5,
        "duration": 25,
    },
    {
        "id": "axon_body_cam_hacks",
        "name": "Hacks des caméras corporelles Axon",
        "distance_label": "Courte portée (≤ 15m)",
        "distance_level": 2,
        "rp_description": "Injecter un signal malformé pour stoper et/ou brouillez les body cams.",
        "tools": ["SDR", "Laptop", "Signal Jammer", "Body Cam Controller", "SADOT Body Cam Maintenance Kit"],
        "risk": 2,
        "duration": 140,
    },
    {
        "id": "911_hacks",
        "name": "Faux apell au 911",
        "distance_label": "San Andreas + Robada",
        "distance_level": 7,
        "rp_description": "Simuler un appel d'urgence pour détourner les ressources policières ou créer une diversion.",
        "tools": ["911 Spoofer", "Laptop", "Voice Changer", "Fake Caller ID", "UTK Police Scanner"],
        "risk": 3,
        "duration": 150,
    },
    {
        "id": "mdt_hacks",
        "name": "Hacks du MDT (Mobile Data Terminal)",
        "distance_label": "San Andreas + Robada",
        "distance_level": 7,
        "rp_description": "Accéder au MDT pour obtenir des informations sur les unités policières, les appels en cours et les emplacements des patrouilles.",
        "tools": ["MDT Exploit Kit", "Police Laptop", "Signal Jammer", "UTK Police Scanner", "Scanner & Reader Radio Frequencies"],
        "risk": 3,
        "duration": 305,
    },
    {
        "id": "poste_police_hacks",
        "name": "Hacks de postes de police",
        "distance_label": "San Andreas + Robada",
        "distance_level": 7,
        "rp_description": "Accéder aux systèmes des postes de police et commissariats pour obtenir des informations sensibles.",
        "tools": ["MDT Exploit Kit", "Police Laptop", "Signal Jammer", "UTK Police Scanner", "Scanner & Reader Radio Frequencies"],
        "risk": 5,
        "duration": 251,
    },
    {
        "id": "flood_911",
        "name": "Flood 911",
        "distance_label": "San Andreas + Robada",
        "distance_level": 7,
        "rp_description": "Envoyer un grand nombre d'appels fictifs au 911 pour surcharger le système.",
        "tools": ["911 Spoofer", "Laptop", "Voice Changer", "Fake Caller ID"],
        "risk": 5,
        "duration": 25,
    },
    {
        "id": "axon_body_cam_hacks",
        "name": "Hacks des caméras corporelles Axon",
        "distance_label": "Courte portée (≤ 15m)",
        "distance_level": 2,
        "rp_description": "Injecter un signal malformé pour stoper et/ou brouillez les body cams.",
        "tools": ["SDR", "Laptop", "Signal Jammer", "Body Cam Controller", "SADOT Body Cam Maintenance Kit"],
        "risk": 2,
        "duration": 140,
    },
    {
        "id": "impound_lot_hack",
        "name": "Système de la fourrière",
        "distance_label": "Portée moyenne (≤ 50m)",
        "distance_level": 3,
        "rp_description": "Infiltrer la base locale de la fourrière pour marquer un véhicule saisi comme libéré sans frais.",
        "tools": ["MDT Exploit Kit", "Police Laptop", "Signal Jammer"],
        "risk": 3,
        "duration": 180,
    },
    {
        "id": "alpr_bypass",
        "name": "Bypass des caméras LAPI (Plaques)",
        "distance_label": "Courte portée (≤ 15m)",
        "distance_level": 2,
        "rp_description": "Injecter un script pour aveugler temporairement les caméras de lecture automatique des plaques de la police.",
        "tools": ["SDR", "Laptop", "Signal Jammer"],
        "risk": 4,
        "duration": 210,
    },
    {
        "id": "mdt_report_injection",
        "name": "Faux rapport d'unité (MDT)",
        "distance_label": "San Andreas + Robada",
        "distance_level": 7,
        "rp_description": "Envoyer une fausse notification de fin de service sur le terminal d'une unité pour qu'elle soit rappelée au poste.",
        "tools": ["MDT Exploit Kit", "Police Laptop", "UTK Police Scanner"],
        "risk": 3,
        "duration": 115,
    },
    {
        "id": "ghost_unit_dispatch",
        "name": "Création d'unité fantôme (Dispatch)",
        "distance_label": "San Andreas + Robada",
        "distance_level": 7,
        "rp_description": "Créer une unité de police virtuelle sur la carte du dispatch pour occuper le répartiteur et retarder les interventions.",
        "tools": ["911 Spoofer", "Laptop", "Fake Caller ID"],
        "risk": 4,
        "duration": 190,
    },
]