TARGETS = [
    {
        "id": "local_lan_server",
        "name": "Serveur local (LAN)",
        "distance_label": "Courte portée (≤ 15m)",
        "distance_level": 2,
        "rp_description": "Scanner le réseau local et exploiter une vulnérabilité connue.",
        "tools": ["Laptop", "Ethernet Tap"],
        "interaction": "bruteforce",
        "minigame_title": "Attaque brute-force LAN",
        "minigame_instruction": "Lancez l'attaque en force sur le port local et laissez le processus converger.",
        "minigame_interaction_hint": "Démarrez le bruteforce, puis surveillez l'avancement jusqu'à 100%.",
        "command_examples": ["nmap -p 22 192.168.1.10", "ssh user@192.168.1.10"],
        "risk": 3,
        "duration": 120,
        "hint": "Maintenir le scanner actif pendant l'exploitation du port.",
    },
    {
        "id": "private_company_server",
        "name": "Serveur entreprise privée",
        "distance_label": "Portée étendue (≤ 2km)",
        "distance_level": 5,
        "rp_description": "Brute-force SSH puis pivoter via un modem 4G anonymisé.",
        "tools": ["Laptop", "4G Modem", "VPN Relay"],
        "interaction": "terminal",
        "minigame_title": "Exploit SSH manuel",
        "minigame_instruction": "Saisissez la commande SSH d'accès à l'aide des indices d'intrusion fournis.",
        "minigame_interaction_hint": "Entrez la commande appropriée et exécutez-la avant que l'alerte ne monte.",
        "command_examples": ["ssh admin@10.0.0.12", "ssh root@10.0.0.12"],
        "risk": 4,
        "duration": 140,
        "hint": "Entrer une commande SSH valide avant que le journal ne détecte l'intrusion.",
    },

    {
        "id": "municipal_database",
        "name": "Base de données municipale",
        "distance_label": "San Andreas complet",
        "distance_level": 6,
        "rp_description": "Simuler une injection SQL et extraire les tables sensibles.",
        "tools": ["Laptop", "Serveur VPS", "VPN Relay"],
        "interaction": "puzzle",
        "minigame_title": "Injection SQL ciblée",
        "minigame_instruction": "Reconstituez la requête manquante à partir des fragments d'injection.",
        "minigame_interaction_hint": "Utilisez les indices pour écrire la bonne requête SQL d'injection.",
        "command_examples": [
            "SELECT id, username FROM users WHERE role='admin';",
            "SELECT * FROM credentials WHERE status='active';",
        ],
        "sql_command": "SELECT id, username FROM users WHERE role='admin';",
        "risk": 5,
        "duration": 170,
        "hint": "Utiliser les indices partiels pour reconstruire la requête d'injection.",
    },
    {
        "id": "police_radio_network",
        "name": "Réseau de communication policier",
        "distance_label": "San Andreas complet",
        "distance_level": 6,
        "rp_description": "Intercepter et déchiffrer les transmissions radio propriétaires.",
        "tools": ["SDR Radio", "Laptop", "Decoder"],
        "interaction": "radio",
        "minigame_title": "Déchiffrage radio policier",
        "minigame_instruction": "Assemblez les fragments dans l'ordre pour reformer le message protégé.",
        "minigame_interaction_hint": "Sélectionnez chaque fragment jusqu'à ce que le message soit lisible.",
        "risk": 5,
        "duration": 160,
        "hint": "Assembler les fragments de signal pour révéler le message codé.",
    },
    {
        "id": "government_infrastructure",
        "name": "Infrastructure gouvernementale",
        "distance_label": "San Andreas + Robada",
        "distance_level": 7,
        "rp_description": "Chaîne complète d'exploits combinant relais, 0-day et insider.",
        "tools": ["Serveur Relay", "0-Day Kit", "Botnet", "Insider"],
        "interaction": "chain",
        "minigame_title": "Chaîne d'exploits gouvernementale",
        "minigame_instruction": "Validez chaque maillon de la chaîne d'intrusion jusqu'à l'accès final.",
        "minigame_interaction_hint": "Avancez étape par étape, chaque action déclenche la suivante.",
        "risk": 5,
        "duration": 200,
        "hint": "Réussir chaque phase pour atteindre la dernière couche de sécurité.",
    },
    {
        "id": "federal_network",
        "name": "Réseau fédéral (FIB / IAA)",
        "distance_label": "San Andreas + Robada",
        "distance_level": 7,
        "rp_description": "Opération niveau max avec botnet et complice interne.",
        "tools": ["0-Day Kit", "Botnet", "Insider"],
        "interaction": "stages",
        "minigame_title": "Progression réseau fédéral",
        "minigame_instruction": "Traversez chaque phase de sécurité jusqu'au niveau fédéral.",
        "minigame_interaction_hint": "Complétez chaque étape dans l'ordre pour éviter l'échec.",
        "risk": 5,
        "duration": 220,
        "hint": "Maintenir la confidentialité tout en progressant étape par étape.",
    },
]
