TARGETS = [
    {
        "id": "local_lan_server",
        "name": "Serveur local (LAN)",
        "distance_label": "Courte portée (≤ 15m)",
        "distance_level": 2,
        "rp_description": "Scanner le réseau local et exploiter une vulnérabilité connue.",
        "tools": ["Laptop", "Ethernet Tap"],
        "interaction": "bruteforce",
        "risk": 3,
        "duration": 120,
        "hint": "Maintenir le scanner actif pendant l'exploitation du port.",
    },
    {
        "id": "private_company_server",
        "name": "Serveur entreprise privée",
        "distance_label": "Portée étendue (≤ 2km)",
        "distance_level": 5,
        "rp_description": "Brute-force SSH puis pivoter via un modem 4G anonymisé.",
        "tools": ["Laptop", "4G Modem", "VPN Relay"],
        "interaction": "terminal",
        "risk": 4,
        "duration": 140,
        "hint": "Entrer une commande SSH valide avant que le journal ne détecte l'intrusion.",
    },
    {
        "id": "municipal_database",
        "name": "Base de données municipale",
        "distance_label": "San Andreas complet",
        "distance_level": 6,
        "rp_description": "Simuler une injection SQL et extraire les tables sensibles.",
        "tools": ["Laptop", "Serveur VPS", "VPN Relay"],
        "interaction": "puzzle",
        "risk": 5,
        "duration": 170,
        "hint": "Utiliser les indices partiels pour reconstruire la requête d'injection.",
    },
    {
        "id": "police_radio_network",
        "name": "Réseau de communication policier",
        "distance_label": "San Andreas complet",
        "distance_level": 6,
        "rp_description": "Intercepter et déchiffrer les transmissions radio propriétaires.",
        "tools": ["SDR Radio", "Laptop", "Decoder"],
        "interaction": "radio",
        "risk": 5,
        "duration": 160,
        "hint": "Assembler les fragments de signal pour révéler le message codé.",
    },
    {
        "id": "government_infrastructure",
        "name": "Infrastructure gouvernementale",
        "distance_label": "San Andreas + Robada",
        "distance_level": 7,
        "rp_description": "Chaîne complète d'exploits combinant relais, 0-day et insider.",
        "tools": ["Serveur Relay", "0-Day Kit", "Botnet", "Insider"],
        "interaction": "chain",
        "risk": 5,
        "duration": 200,
        "hint": "Réussir chaque phase pour atteindre la dernière couche de sécurité.",
    },
    {
        "id": "federal_network",
        "name": "Réseau fédéral (FIB / IAA)",
        "distance_label": "San Andreas + Robada",
        "distance_level": 7,
        "rp_description": "Opération niveau max avec botnet et complice interne.",
        "tools": ["0-Day Kit", "Botnet", "Insider"],
        "interaction": "stages",
        "risk": 5,
        "duration": 220,
        "hint": "Maintenir la confidentialité tout en progressant étape par étape.",
    },
]
