TARGETS = [
    {
        "id": "local_lan_server",
        "name": "Serveur local entreprise (LAN-PRO)",
        "distance_label": "Courte portée (≤ 15m)",
        "distance_level": 2,
        "rp_description": "Scanner le réseau local et exploiter une vulnérabilité connue en Zero Day.",
        "tools": ["Laptop", "Ethernet Tap", "Bypass Kit", "internet access with infected USB driver internet port"],
        "risk": 1,
        "duration": 200,
    },
    {
        "id": "private_company_server",
        "name": "Serveur entreprise privée crypté (VPN-REQUIRED)",
        "distance_label": "Portée étendue (≤ 2km)",
        "distance_level": 5,
        "rp_description": "Brute-force SSH puis pivoter via un modem 4G anonymisé.",
        "tools": ["Laptop", "4G Modem", "VPN Relay"],
        "risk": 4,
        "duration": 350,
    },
    {
        "id": "police_radio_network",
        "name": "Réseau de communication policier",
        "distance_label": "San Andreas complet",
        "distance_level": 6,
        "rp_description": "Intercepter et déchiffrer les transmissions radio propriétaires.",
        "tools": ["SDR Radio", "Laptop", "Decoder", "Scanner & Reader Radio Frequencies", "UTK Police Scanner"],
        "risk": 0,
        "duration": 100,
    },
    {
        "id": "government_infrastructure",
        "name": "Infrastructure médicale / hospitalière",
        "distance_label": "San Andreas + Robada",
        "distance_level": 7,
        "rp_description": "Chaîne complète d'exploits combinant relais, 0-day et insider.",
        "tools": ["Serveur Relay", "0-Day Kit", "Botnet", "Insider"],
        "risk": 5,
        "duration": 998,
    },
    {
        "id": "government_infrastructure",
        "name": "Infrastructure gouvernementale (Hors USSS)",
        "distance_label": "San Andreas + Robada",
        "distance_level": 7,
        "rp_description": "Chaîne complète d'exploits combinant relais, 0-day et insider.",
        "tools": ["Serveur Relay", "0-Day Kit", "Botnet", "Insider"],
        "risk": 5,
        "duration": 1000,
    },
    {
        "id": "local_police_network",
        "name": "Réseau police local (LSPD + LSSD)",
        "distance_label": "San Andreas + Robada",
        "distance_level": 7,
        "rp_description": "Opération niveau max avec botnet.",
        "tools": ["Serveur Relay", "0-Day Kit", "Botnet", "Insider"],
        "risk": 5,
        "duration": 548,
    },
    {
        "id": "ethatique_network",
        "name": "Réseau éthatique (SAHP / RHP)",
        "distance_label": "San Andreas + Robada",
        "distance_level": 7,
        "rp_description": "Opération niveau max avec botnet.",
        "tools": ["Serveur Relay", "0-Day Kit", "Botnet", "Insider"],
        "risk": 5,
        "duration": 684,
    },
    {
        "id": "federal_network",
        "name": "Réseau fédéral (FIB / USNPS / NOOSE)",
        "distance_label": "San Andreas + Robada",
        "distance_level": 7,
        "rp_description": "Opération niveau max avec botnet.",
        "tools": ["Serveur Relay", "0-Day Kit", "Botnet", "Insider"],
        "risk": 5,
        "duration": 750,
    },
    {
        "id": "federal_network",
        "name": "Réseau gouvernemental (USSS)",
        "distance_label": "San Andreas + Robada",
        "distance_level": 7,
        "rp_description": "Opération niveau max avec botnet.",
        "tools": ["Serveur Relay", "0-Day Kit", "Botnet", "Insider"],
        "risk": 5,
        "duration": 1000,
    },
    {
        "id": "clean_logs",
        "name": "Effacement des sauvegardes de logs (Log Purge Pro)",
        "distance_label": "San Andreas + Robada",
        "distance_level": 7,
        "rp_description": "Opération niveau max avec botnet.",
        "tools": ["Laptop", "Serveur Relay", "0-Day Kit", "Botnet"],
        "risk": 5,
        "duration": 150,
    },
]