TARGETS = [
    {
        "id": "vehicle_unlock",
        "name": "Déverrouillage portières",
        "distance_label": "Proximité (≤ 2m)",
        "distance_level": 1,
        "rp_description": "Contact physique requis pour accéder au port OBD et aux verrous.",
        "tools": ["Flipper Zero", "OBD Dongle"],
        "interaction": "sequence",
        "minigame_title": "Clonage d'accès porte",
        "minigame_instruction": "Reproduisez la séquence RFID affichée par le lecteur pour ouvrir les verrous.",
        "minigame_interaction_hint": "Appuyez sur les boutons dans le même ordre que la séquence cible.",
        "risk": 2,
        "duration": 90,
        "hint": "Reproduire la séquence de touches à l'emplacement du lecteur RFID.",
    },
    {
        "id": "vehicle_start_no_key",
        "name": "Démarrage sans clé",
        "distance_label": "Proximité (≤ 2m)",
        "distance_level": 1,
        "rp_description": "Accéder à l'ECU via un dongle OBD et contourner l'antidémarrage.",
        "tools": ["OBD Dongle", "Laptop"],
        "interaction": "wiring",
        "minigame_title": "Câblage OBD",
        "minigame_instruction": "Reliez chaque fil du module OBD à la bonne broche pour activer l'ECU.",
        "minigame_interaction_hint": "Sélectionnez un fil puis la prise correspondante pour construire le circuit de démarrage.",
        "risk": 3,
        "duration": 120,
        "hint": "Relier les bons fils selon l'ordre de l'ECU pour amorcer le démarrage.",
    },
    {
        "id": "vehicle_gps_suppress",
        "name": "Désactivation traceur GPS",
        "distance_label": "Courte portée (≤ 15m)",
        "distance_level": 2,
        "rp_description": "Scanner et neutraliser le signal du traceur sans éveiller les suspicions.",
        "tools": ["SDR Antenna", "RF Jammer"],
        "interaction": "frequency",
        "minigame_title": "Balayage GPS",
        "minigame_instruction": "Ajustez le curseur de fréquence jusqu'à ce que le traceur soit désynchronisé.",
        "minigame_interaction_hint": "Faites glisser le curseur, puis lancez le scan lorsque la lecture est stable.",
        "risk": 3,
        "duration": 100,
        "hint": "Chercher le bon signal en balayant la bande de fréquences active.",
    },
    {
        "id": "vehicle_plate_clone",
        "name": "Clonage plaque immatriculation",
        "distance_label": "Proximité (≤ 2m)",
        "distance_level": 1,
        "rp_description": "Capturer les données RFID de la plaque et répliquer une nouvelle balise.",
        "tools": ["Laptop", "RFID Cloner"],
        "interaction": "terminal",
        "minigame_title": "Terminal de clonage RFID",
        "minigame_instruction": "Tapez la commande de duplication appropriée pour cloner l'identifiant RFID.",
        "minigame_interaction_hint": "Entrez la commande correcte dans le terminal puis exécutez-la.",
        "risk": 2,
        "duration": 80,
        "hint": "Envoyer les commandes au cloneur pour dupliquer les identifiants RFID.",
    },
    {
        "id": "vehicle_edr_access",
        "name": "Accès boîte noire / EDR",
        "distance_label": "Proximité (≤ 2m)",
        "distance_level": 1,
        "rp_description": "Extraire les journaux de bord et filtrer les données sensibles.",
        "tools": ["OBD Dongle", "Laptop"],
        "interaction": "stages",
        "minigame_title": "Extraction EDR en phases",
        "minigame_instruction": "Complétez chaque phase du protocole d'accès jusqu'à l'extraction finale.",
        "minigame_interaction_hint": "Cliquez sur chaque étape dans l'ordre jusqu'à ce que l'accès soit obtenu.",
        "risk": 4,
        "duration": 150,
        "hint": "Passer par plusieurs phases pour déverrouiller l'EDR et extraire les logs.",
    },
    {
        "id": "vehicle_nav_hack",
        "name": "Piratage système de navigation",
        "distance_label": "Courte portée (≤ 15m)",
        "distance_level": 2,
        "rp_description": "Injecter de fausses coordonnées et détourner le guidage du véhicule.",
        "tools": ["GPS Spoofer", "Laptop"],
        "interaction": "puzzle",
        "minigame_title": "Reconstruction GPS",
        "minigame_instruction": "Assemblez les fragments de trajectoire pour reconstruire le code de navigation.",
        "minigame_interaction_hint": "Utilisez les indices partiels pour rétablir le bon itinéraire.",
        "risk": 3,
        "duration": 110,
        "hint": "Reconstuire le code de navigation à partir d'indices partiels.",
    },
]
