TARGETS = [
    {
        "id": "vehicle_unlock",
        "name": "Déverrouillage portières",
        "distance_label": "Proximité (≤ 2m)",
        "distance_level": 1,
        "rp_description": "Contact physique requis pour accéder au port OBD et aux verrous.",
        "tools": ["Flipper Zero", "OBD Dongle"],
        "interaction": "sequence",
        "risk": 2,
        "duration": 90,
        "hint": "Reproduire la séquence de touches à l'emplacement du lecteur RFID.",
    },
    {
        "id": "vehicle_start_no_key",
        "name": "Démarrage sans clé",
        "distance_label": "Proximité (≤ 2m)",
        "distance_level": 1,
        "rp_description": "Accéder à l'ECU via un dongle OBD et contourner l'antidémarrage.",
        "tools": ["OBD Dongle", "Laptop"],
        "interaction": "wiring",
        "risk": 3,
        "duration": 120,
        "hint": "Relier les bons fils selon l'ordre de l'ECU pour amorcer le démarrage.",
    },
    {
        "id": "vehicle_gps_suppress",
        "name": "Désactivation traceur GPS",
        "distance_label": "Courte portée (≤ 15m)",
        "distance_level": 2,
        "rp_description": "Scanner et neutraliser le signal du traceur sans éveiller les suspicions.",
        "tools": ["SDR Antenna", "RF Jammer"],
        "interaction": "frequency",
        "risk": 3,
        "duration": 100,
        "hint": "Chercher le bon signal en balayant la bande de fréquences active.",
    },
    {
        "id": "vehicle_plate_clone",
        "name": "Clonage plaque immatriculation",
        "distance_label": "Proximité (≤ 2m)",
        "distance_level": 1,
        "rp_description": "Capturer les données RFID de la plaque et répliquer une nouvelle balise.",
        "tools": ["Laptop", "RFID Cloner"],
        "interaction": "terminal",
        "risk": 2,
        "duration": 80,
        "hint": "Envoyer les commandes au cloneur pour dupliquer les identifiants RFID.",
    },
    {
        "id": "vehicle_edr_access",
        "name": "Accès boîte noire / EDR",
        "distance_label": "Proximité (≤ 2m)",
        "distance_level": 1,
        "rp_description": "Extraire les journaux de bord et filtrer les données sensibles.",
        "tools": ["OBD Dongle", "Laptop"],
        "interaction": "stages",
        "risk": 4,
        "duration": 150,
        "hint": "Passer par plusieurs phases pour déverrouiller l'EDR et extraire les logs.",
    },
    {
        "id": "vehicle_nav_hack",
        "name": "Piratage système de navigation",
        "distance_label": "Courte portée (≤ 15m)",
        "distance_level": 2,
        "rp_description": "Injecter de fausses coordonnées et détourner le guidage du véhicule.",
        "tools": ["GPS Spoofer", "Laptop"],
        "interaction": "puzzle",
        "risk": 3,
        "duration": 110,
        "hint": "Reconstuire le code de navigation à partir d'indices partiels.",
    },
]
