TARGETS = [
    {
        "id": "vehicle_start_no_key",
        "name": "Démarrage sans clé",
        "distance_label": "Proximité (≤ 2m)",
        "distance_level": 1,
        "rp_description": "Accéder à l'ECU via un dongle OBD et contourner l'antidémarrage.",
        "tools": ["OBD Dongle", "Laptop", "ECU crack card"],
        "risk": 0,
        "duration": 10,
    },
    {
        "id": "vehicle_gps_suppress",
        "name": "Désactivation traceur GPS",
        "distance_label": "Courte portée (≤ 15m)",
        "distance_level": 2,
        "rp_description": "Scanner et neutraliser le signal du traceur sans éveiller les suspicions.",
        "tools": ["SDR Antenna", "RF Jammer"],
        "risk": 0,
        "duration": 35,
    },
    {
        "id": "vehicle_plate_clone",
        "name": "Clonage plaque immatriculation",
        "distance_label": "Proximité (≤ 2m)",
        "distance_level": 1,
        "rp_description": "Capturer les données RFID de la plaque et répliquer une nouvelle balise.",
        "tools": ["Laptop", "RFID Cloner"],
        "risk": 0,
        "duration": 80,
    },
    {
        "id": "vehicle_edr_access",
        "name": "Accès boîte noire / EDR Transporteur",
        "distance_label": "Proximité (≤ 2m)",
        "distance_level": 1,
        "rp_description": "Extraire les journaux de bord et filtrer les données sensibles.",
        "tools": ["OBD Dongle", "Laptop", "Pirated Black Box"],
        "risk": 2,
        "duration": 130,
    },
]